project:
  type: website
  output-dir: _site
  
website: 
  navbar: 
    right: 
      - text: "**carnet**"
        href: /

metadata-files:
  - system/fragments/default.yml
  - system/fragments/notebook.yml
  - system/fragments/lang-fr.yml